server:
  port: 8000
spring:
  application:
    name: atguigu-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.201.100
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:  pay:    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmthQwmxlCowktqwc+237Enxs7FfNoVMi9BlCA430Vor2Z1IPIDOOdarYdOQLMxl/PxZfgl/6iMRJB43kzfPVFezJ9xim8AC07ZCVi1NZop3q6qhL3s7w5o809BvkaIVnThpSfvifO3wUxBImXwnSfLaD9CMjtNbD4ri1sDQ3CV+g66nR3oIQTfEMAif7GafDkt4nnG+lcd7tOoOsM+6anP8t6M+KDzcpBZ3wsPEIlJVIQgLbBx61g5QZ/p+piDwl0h85QTnz68qHXCE3JRn8MDWOarKEQkFXbuAis2YbJ8agVDpBomrok2i71jdJn863TLsvB76kRjeq1Ygf5YhQWQIDAQAB
    merchant-private-key: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDQcMyQIyGy2yh7xVrDkXeobY9OHR8qXCgrbVZGlBKUhbWlKSHAFfZrpZzqAT01O7v95pLnbB5wnPVXLcAJSq/AZCaQHJR99yYCJuqe/XF/GrnDHWFAj84+q0G1yGpDZaf00jxLG+vNyYIYUHzMyijk0VDHEOGg6AjawTO0Zm01QyDTEeLvO3F5LqOVP7eTOM9p3OxV0+YoEIz9fRYHwkTORLqyuYSg6kiMxIvdUpGHQbpe4E4xy+oG0A8E3TG626DwX7zdHMVbbA+nErWq2x8Tgx500PjZab1GiBvk6fIWLTESlwvqd9HNyqai7szYqDpUS5xkqX+2ptctIeybbWffAgMBAAECggEBAJc+4hBMja08PRniUEPMD+lU5kEl/HE+QZ+RTKMV2o2OoAlh2S2KQi5GE5/wmjtARt6rKjlmSIgqPBOwDMIxQWn2wcycEFt+tEOnfWM0P+CcweIENYclUeBDYADJleGlp8OLsVhGwEmoSA/gh04J+rZd86EebLnW5GXm/t+N2vxjk4y2H3IfdNaG2yQFX9SpKOW69RWenDfNi6T4Dgfjy2sJB/f9f6OGRM5trbAOk+NsjGjqxVrVhUwnYmSQ2p7mPx7V3lcy3WgBNMcecCdRFj6CqB40bFqV6y6M0RQQEeckBbEHmJ/JQfWIo47JI6chT3IaPvQ5ug42D+mcJKHp7QECgYEA8tYCZDBhT99ThMzf94i5J5JDe9BNJWCxaa1ucmvgxdm+hRq8vVYXfJ0evA7X7Zg2KoubYhELNqAO3lG6oddXepWylIejlsxXIRJLcdB2BTS7xbOFzvo8eS6PTirwHupGf+ieuaY/Q/inbxX/UMqeCGLZkqpm/f9oALqgNhMV2MECgYEA2712niaS3HqUjpnb7GOONvANJRvEQ50UzrzKsh9rLGyETFlZfhr/ipFUKAqIycHYG85dMGbZnT7I8zjcj7I+OxBDKevufh7FXJ17auI8t64WOF/7L3nOirA8E3UrocGtXZkN0EXIYIhjpl1VBeZIsVaGZGQ4KIvYH2S8W6PFyJ8CgYEAn8YPbLwoStU1rnreIY/jwxWJMT2shJtKH63srXwtOAA8Snd9F1Y9vc/jGPjrOXicqwGQCsYMCrTlE4HSuglllVJJXVChYeawrSHMYeY2wNYhdcLYl4Yto83unA/ETZL3L9FuHdg0aBSClaRziETIFdx0KvvTJ+uUEma4YtvL1AECgYEAmBJPw/V4D6O5qdKrE7Z2VmjdAABuXEiafNTFBm6d8hmLmXcAazht/0zCTA+2SMKhN+UiMvwKwDsSQNjqM3wsex2vDZUc8SWEeqr2HatCT+/nqs4p/No0aWC7ws+FCaYKv8rLd4bDvKLHK/xNeg674ha6XUHKZ60YPemuPVFi8IsCgYEAssHWMReodRfdbtHSSVR364LAooB8zOfiB0v4huR9Yhtef5UtOew4Y1FsMcu5lWtcde6cRa3hW1yHJ1EsECDayJjAixNO5aRgd7BayUeYx8nUQvwb2z4+EaFRT6/a+uMGMlOgOHuacg1F0OJcvU17HWafOdGOCIvpXKkP5vFbfS4=
    app-id: 2016080400166558
    charset: "UTF-8"
    gateway-url: https://openapi.alipaydev.com/gateway.do
    notify-url: http://xdu74j.natappfree.cc/pay/notify
    return-url: http://xdu74j.natappfree.cc/pay/return
    sign-type: RSA2